# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
    config,
    lib,
    pkgs,
    modulesPath,
    ...
}:

{
    imports = [
        (modulesPath + "/installer/scan/not-detected.nix")
    ];

    boot.initrd.availableKernelModules = [
        "xhci_pci"
        "ahci"
        "usbhid"
        "sd_mod"
    ];
    boot.initrd.kernelModules = [ ];
    boot.kernelModules = [ "kvm-intel" ];
    boot.extraModulePackages = [ ];

    fileSystems."/" = {
        device = "/dev/disk/by-uuid/289fcbfd-9582-4bd9-9c0d-0124dc1bc5d9";
        fsType = "ext4";
    };

    fileSystems."/bin" = {
        device = "/usr/bin";
        fsType = "none";
        options = [ "bind" ];
    };

    fileSystems."/boot" = {
        device = "/dev/disk/by-uuid/7277-A699";
        fsType = "vfat";
        options = [
            "fmask=0077"
            "dmask=0077"
        ];
    };

    fileSystems."/mnt/stuff" = {
        device = "/dev/disk/by-uuid/49de2a1b-812d-4a23-add5-fd01fd09d78f";
        fsType = "ext4";
    };

    swapDevices = [
        { device = "/dev/disk/by-uuid/748efabb-0cb3-4b71-9475-10f80d6c58cf"; }
    ];

    nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
    hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
