set -g default-terminal "xterm-256color"
set -as terminal-overrides ",xterm*:colors=256"
set -ag terminal-overrides ",xterm*:Tc"
set -as terminal-features ",xterm*:RGB"
set -g allow-passthrough on
set -g status-style "bg=#245b97"
set -g message-style "fg=black bg=#bc9ed0"
set -g default-command "${SHELL}"
bind | split-window -h
bind - split-window -v
bind r source-file ~/.tmux.conf
unbind %
unbind '"'
set -g mouse on
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix
