#! /bin/sh

xmodmap ~/.Xmodmap
pgrep -x sxhkd > /dev/null || sxhkd &

pgrep -x conky > /dev/null || conky -p 5 &
(sleep 6; xdo lower -N Conky) &

pgrep -x diodon > /dev/null || diodon &
pgrep -x redshift-gtk > /dev/null || (sleep 3; redshift-gtk) &

# xfce4-panel --disable-wm-check &
pgrep -x polybar > /dev/null || polybar &
picom -b

xsettingsd &

dunst &
nm-applet &
blueman-applet &

# pgrep -x protonvpn-app > /dev/null || (sleep 3; gtk-launch proton.vpn.app.gtk) &
# pgrep -x whatpulse > /dev/null || (sleep 3; whatpulse --minimized --closedwindow) &

# bspc monitor DP-5 -d 1 2 3 4 5 6
# bspc monitor HDMI-0 -d 7 8 9 10 11 12
bspc monitor -d 1 2 3 4 5 6 7 8 9 10 11 12
bspc config border_width         6
bspc config window_gap           6

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config automatic_scheme spiral
bspc config top_padding 32
bspc config presel_feedback_color '#BC9ED0'
bspc config focused_border_color '#F08533'
bspc config normal_border_color '#245B97'
bspc config active_border_color '#BC9ED0'

bspc rule -a Chromium desktop='^6'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Xfce4-panel manage=off border=off layer=above
#bspc rule -a Conky state=floating sticky=on layer=below
bspc rule -a Conky manage=off
bspc rule -a 'Wrapper-2.0' state=floating border=off focus=on
