#! /bin/sh
# xsetroot -cursor_name left_ptr
xrandr --output DP-5 --primary --output HDMI-0 --right-of DP-5
xmodmap ~/.Xmodmap
# pgrep -x sxhkd > /dev/null || sxhkd &
# lxqt-policykit-agent &
pgrep -x greenclip || greenclip daemon &
# systemctl --user import-environment DISPLAY XAUTHORITY WAYLAND_DISPLAY
# dbus-update-activation-environment --systemd DISPLAY XAUTHORITY WAYLAND_DISPLAY

# pgrep -x conky > /dev/null || conky -p 7 &
(sleep 3; xdo lower -N Conky) &

# pgrep -x diodon > /dev/null || diodon &
# pgrep -x redshift-gtk > /dev/null || (sleep 3; redshift-gtk) &

# xfce4-panel --disable-wm-check &
pgrep -x polybar > /dev/null || polybar top &
# picom -b

# pkill dunst && dunst &
# xsettingsd &

feh --bg-fill ~/Pictures/wallpaper/wallpaper.png
nm-applet &
# blueman-applet &

# pgrep -x protonvpn-app > /dev/null || (sleep 3; gtk-launch proton.vpn.app.gtk) &
protonvpn connect &
pgrep -x whatpulse > /dev/null || (sleep 3; flatpak run org.whatpulse.WhatPulse --minimized --closedwindow) &

bspc monitor DP-5 -d 󰇊 󰇋 󰇌 󰇍 󰇎 󰇏
bspc monitor HDMI-0 -d 󱅊 󱅋 󱅌 󱅍 󱅎 󱅏
bspc config border_width        4
bspc config window_gap          12

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config automatic_scheme longest_side
# bspc config focus_follows_pointer true
bspc config pointer_follows_focus true
bspc config -m DP-5 top_padding 44
bspc config presel_feedback_color '#cfb793'
bspc config focused_border_color '#F08533'
bspc config normal_border_color '#245B97'
bspc config active_border_color '#BC9ED0'

# bspc rule -a Chromium desktop='^6'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Xfce4-panel manage=off border=off layer=above
#bspc rule -a Conky state=floating sticky=on layer=below
bspc rule -a Gsimplecal sticky=on
bspc rule -a Conky manage=off
bspc rule -a 'Wrapper-2.0' state=floating border=off focus=on

notify-send "bspwm" "Configuration loaded"
